// <auto-generated />
namespace StudentOnlineLeaveSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Check01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Check01));
        
        string IMigrationMetadata.Id
        {
            get { return "201512230135342_Check01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
